// MongoDB connection
const mongo = require('./db.js')
const db = mongo.get()

const mongojs = require('mongojs')

/**
 * Function that fetches all documents from the DB to show on the main page of the application.
 * @param callback Function that gets called after the search in the DB is done.
 */
exports.getDataFromDB = function (callback) {
    db.people.find(function (err, results) {
        callback(results)
    })
}

/**
 * Function that returns the Mongo Object that belongs to the ID given in the parameters.
 * @param id The ID of the document generated by MongoDB.
 * @param callback Function that gets after the search is done in the DB that returns the right document.
 */
exports.findById = function (id, callback) {
    db.people.findOne({_id: mongojs.ObjectId(id)}, function (err, personDocument) {
        callback(personDocument)
    })
}

/**
 * Searches throught the daycares DB for a daycare by ID.
 * @param id The ID of the daycare venue.
 * @param callback callback function that returns the data when found.
 */
exports.getDaycares = function (id, callback) {
    db.daycares.findOne({_id: mongojs.ObjectId(id)}, function (err, daycare_info) {
        callback(daycare_info)
    })
}

//TODO THIS IS GONNA BE IN A ROUTE CALLED BY THE SUBMIT BUTTON
// function daycare_pref_submitted() {
//     // ID of the chosen daycare venue
//     let choice = document.querySelector('input[name="daycare_prefrence"]:checked').value
//
//     // ID of the applicant that has chosen the daycare venue
//     let id = document.querySelector('div#basic_info').querySelector('#id_code').innerHTML.slice(-24)
//
//     //TODO change/add choice to DB
//
//     //TODO change status
//     changeStatus(id, "closed")
// }
//
//
// function changeStatus(id, status) {
//     db.people.findAndModify({
//         query: { '_id': mongojs.ObjectId(id) },
//         update: { $set: { 'status': status }},
//         new: true
//     }, function (err, doc) {
//
//         return
//     })
// }
